from pd_explain.llm_integrations.llm_integration_interface import LLMIntegrationInterface

class QueryRefiner(LLMIntegrationInterface):
    """
    QueryRefiner is based on the query refinement process in OmniTune (see paper "OmniTune: A universal framework for query refinement via LLMs"
    by Eldar Hacohen, Yuval Moskovitch, Amit Somech).
    We use this in the context of query recommenders to refine the queries that are generated by the query
    recommenders.
    """

    pass